# Minimal Nixpacks configuration for VibeX
# Let Railway auto-detect Python and Node.js

[start]
cmd = "cd web && npx concurrently \"cd .. && python -m vibex start --host 0.0.0.0 --port $PORT\" \"pnpm run start\""

[variables]
PORT = "7770"
