# Nixpacks configuration for VibeX
# This deploys both the API server and Web interface

[phases.setup]
nixPkgs = ["python311", "nodejs_20", "pnpm", "git"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    # Install Python dependencies
    "pip install uv",
    "uv pip install -e .",

    # Install Web dependencies
    "cd web && pnpm install --frozen-lockfile",
    "pnpm add -g concurrently",
]

[phases.build]
dependsOn = ["install"]
cmds = [
    # Build Web interface
    "cd web && pnpm run build",
]

[start]
# Start the API server (Web interface can be deployed separately)
cmd = "concurrently \"python -m vibex start --host 0.0.0.0 --port $PORT\" \"cd web && pnpm run start\""

[variables]
PYTHONUNBUFFERED = "1"
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
PORT = "7770"
WEB_PORT = "7777"
