[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "roboco"
version = "0.2.0"
description = "Robotic Co-Workers (RoboCo) framework for specialized AI workers"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache"}
authors = [
    {name = "RoboCo Team", email = "hi@dustland.ai"}
]
dependencies = [
    "ag2[openai,browser]>=0.8.1",
    "openai>=1.3.0",
    "langchain>=0.1.0",
    "langchain-core>=0.1.0",
    "loguru>=0.7.0",
    "tavily-python>=0.3.0",
    "tomli>=2.0.0",
    "pydantic>=2.0.0",
    "requests>=2.0.0",
    "browser-use>=0.1.40",
    "playwright>=1.38.0",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["roboco"]

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.mypy]
python_version = "3.10"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
disallow_untyped_defs = false
