loaders:
  - type: python
    search_path: [src]
    modules: [agentx.core]
    ignore_when_discovered: ["__pycache__"]

processors:
  - type: filter
    expression: not name.startswith("_") or name == "__init__"
    do_not_filter_modules: false
  - type: smart
  - type: crossref

renderer:
  type: markdown
  filename: temp_api_docs/core.md
  render_module_header: true
  render_toc: true
  signature_code_block: true
  signature_in_header: false
  code_headers: true
  descriptive_class_title: true
  descriptive_module_title: true
  add_method_class_prefix: true
  add_member_class_prefix: true
