name: "AutoWriter Production Team"
description: "A professional multi-agent system that produces superior, consulting-quality HTML reports from a single objective."

# LLM Configuration
llm_config:
  model: "deepseek/deepseek-chat"
  temperature: 0.3
  max_tokens: 4000

# All agents are presets, using the detailed, high-quality prompts we developed.
# Note: Planning is handled by the orchestrator's Brain, not a separate agent.
agents:
  - "researcher" # Gathers and synthesizes rigorous, evidence-based research.
  - "writer" # Transforms research into a clear, persuasive, C-suite ready narrative.
  - "web_designer" # Architects the final, world-class interactive HTML experience.
  - "reviewer" # Provides final, uncompromising quality assurance on the HTML output.

handoffs:
  - from_agent: "researcher"
    to_agent: "writer"
    condition: "When research is complete and writing is needed"
  - from_agent: "writer"
    to_agent: "web_designer"
    condition: "When the written content is complete and web design is needed"
  - from_agent: "web_designer"
    to_agent: "reviewer"
    condition: "When the web page is complete and review is needed"
