# AutoWriter Team Configuration
# Professional multi-agent system for comprehensive research and publication-quality reporting

name: "AutoWriter Professional Research Team"
description: "Multi-agent system for data-driven research and professional report generation with interactive visualizations"
output_dir: "workspace"

agents:
  - name: research_planner
    description: "Professional research strategy and comprehensive planning specialist"
    class: agentx.core.agents.Agent
    prompt_template: "prompts/research_planner.md"
    llm_config:
      model: deepseek/deepseek-chat
      temperature: 0.2
      max_tokens: 4096
    tools:
      - write_file

  - name: search_specialist
    description: "Authoritative source identification and quantitative data gathering specialist"
    class: agentx.core.agents.Agent
    prompt_template: "prompts/search_specialist.md"
    llm_config:
      model: deepseek/deepseek-chat
      temperature: 0.1
      max_tokens: 2048
    tools:
      - web_search
      - write_file

  - name: content_extractor
    description: "Quantitative data extraction and structured analysis specialist"
    class: agentx.core.agents.Agent
    prompt_template: "prompts/content_extractor.md"
    llm_config:
      model: deepseek/deepseek-chat
      temperature: 0.15
      max_tokens: 4096
    tools:
      - extract_content
      - read_file
      - write_file

  - name: research_synthesizer
    description: "Cross-source data integration and pattern analysis specialist"
    class: agentx.core.agents.Agent
    prompt_template: "prompts/research_synthesizer.md"
    llm_config:
      model: deepseek/deepseek-reasoner
      temperature: 0.3
      max_tokens: 6144
    tools:
      - read_file
      - write_file

  - name: content_reasoner
    description: "Deep analytical reasoning and insight generation specialist"
    class: agentx.core.agents.Agent
    prompt_template: "prompts/content_reasoner.md"
    llm_config:
      model: deepseek/deepseek-reasoner
      temperature: 0.25
      max_tokens: 8192
    tools:
      - read_file
      - write_file

  - name: document_formatter
    description: "Professional HTML report generation with interactive visualizations"
    class: agentx.core.agents.Agent
    prompt_template: "prompts/document_formatter.md"
    llm_config:
      model: deepseek/deepseek-chat
      temperature: 0.1
      max_tokens: 6144
    tools:
      - read_file
      - write_file

# Enhanced handoffs for professional research workflow
handoffs:
  - from_agent: "research_planner"
    to_agent: "search_specialist"
    condition: "comprehensive research plan is complete with 6-8 sub-queries defined"

  - from_agent: "search_specialist"
    to_agent: "content_extractor"
    condition: "authoritative sources with quantitative data have been identified and documented"

  - from_agent: "content_extractor"
    to_agent: "search_specialist"
    condition: "additional sub-queries require source gathering and data collection"

  - from_agent: "content_extractor"
    to_agent: "research_synthesizer"
    condition: "all sub-queries have quantitative data extracted and ready for synthesis"

  - from_agent: "research_synthesizer"
    to_agent: "content_reasoner"
    condition: "data synthesis is complete and ready for deep analytical reasoning"

  - from_agent: "content_reasoner"
    to_agent: "document_formatter"
    condition: "analytical reasoning is complete with insights and recommendations ready for professional formatting"

  - from_agent: "document_formatter"
    to_agent: "COMPLETE"
    condition: "professional HTML report with interactive visualizations is complete and ready for delivery"

# Team-level configuration
after_work_behavior: "return_to_user"

# Orchestrator configuration for intelligent routing
orchestrator:
  max_rounds: 60
  timeout: 9600 # 2.67 hours for comprehensive professional research
  llm_config:
    model: deepseek/deepseek-chat
    temperature: 0.1
    max_tokens: 1024
    timeout: 45

# Execution configuration
execution:
  mode: "autonomous"
  max_rounds: 60
  timeout_seconds: 9600 # 2.67 hours for comprehensive research and professional report generation
  initial_agent: "research_planner"
