agents:
- description: Requirements gathering and project planning specialist
  llm_config:
    max_tokens: 4096
    model: deepseek/deepseek-chat
    temperature: 0.7
  name: consultant
  prompt_template: prompts/consultant.md
description: Test consultant agent only
execution:
  initial_agent: consultant
  max_rounds: 5
  mode: autonomous
  timeout_seconds: 300
name: consultant_test
