# SuperWriter Team Configuration
# Multi-agent system for comprehensive research report generation

name: "SuperWriter Research Team"
description: "Advanced multi-agent system for comprehensive research report generation"

agents:
  - name: consultant
    description: "Requirements gathering and project planning specialist"
    prompt_template: "prompts/consultant.md"
    llm_config:
      model: deepseek/deepseek-chat
      temperature: 0.3
      max_tokens: 4096

  - name: researcher
    description: "Research specialist for comprehensive information gathering"
    prompt_template: "prompts/researcher.md"
    llm_config:
      model: deepseek/deepseek-chat
      temperature: 0.2
      max_tokens: 4096

  - name: writer
    description: "Professional content writer for long-form research reports"
    prompt_template: "prompts/writer.md"
    llm_config:
      model: deepseek/deepseek-chat
      temperature: 0.4
      max_tokens: 4096

  - name: reviewer
    description: "Quality assurance and editorial review specialist"
    prompt_template: "prompts/reviewer.md"
    llm_config:
      model: deepseek/deepseek-chat
      temperature: 0.1
      max_tokens: 4096

# Multi-agent handoffs
handoffs:
  - from_agent: "consultant"
    to_agent: "researcher"
    condition: "requirements are clear and research is needed"

  - from_agent: "researcher"
    to_agent: "writer"
    condition: "research is complete and writing should begin"

  - from_agent: "writer"
    to_agent: "reviewer"
    condition: "draft is complete and ready for review"

  - from_agent: "reviewer"
    to_agent: "writer"
    condition: "revisions are needed"

# Orchestrator configuration with proper brain setup
orchestrator:
  max_rounds: 20
  timeout: 1800
  brain_config:
    model: deepseek/deepseek-chat
    temperature: 0.0
    max_tokens: 100
    timeout: 15

# Execution configuration
execution:
  mode: "autonomous"
  max_rounds: 20
  timeout_seconds: 1800
  initial_agent: "consultant"
