description: A team that works with data analysis
name: DataTeam
output_dir: workspace/data_analysis
roles:
- product_manager
- data_analyst
- report_writer
tools:
- filesystem
workflow:
- from: product_manager
  to: data_analyst
- from: data_analyst
  to: report_writer
- from: report_writer
  to: product_manager
