# Roboco Robotics Corporation Configuration Example
# This file serves as a template for configuring the Roboco system.
# Copy this file to config.yaml and modify the settings as needed.
#
# cp config/config.example.yaml config/config.yaml

# Company Information
company:
  name: "Roboco Robotics Corporation"
  vision: "To be the greatest robotics company in the world"

# Core Settings
core:
  workspace_base: "./workspace"
  debug: false
  cache_dir: "./cache"
  research_output_dir: "./research_output"
  workspace_root: "workspace"

# LLM Settings
llm:
  # Global LLM configuration (default for all agents)
  model: "deepseek-chat"
  api_key: "${DEEPSEEK_API_KEY}" # Set in environment or .env file
  max_tokens: 4000
  temperature: 0.7
  base_url: "https://api.deepseek.com/v1"
  terminate_msg: "TERMINATE"

  # Vision-capable models
  vision:
    model: "gpt-4o"
    api_key: "${OPENAI_API_KEY}"
    base_url: "https://api.openai.com/v1"
    max_tokens: 4000
    temperature: 0.7

  # OpenAI models
  openai:
    model: "gpt-4o"
    base_url: "https://api.openai.com/v1"
    api_key: "${OPENAI_API_KEY}"
    max_tokens: 4096
    temperature: 0.7

  # DeepSeek models
  deepseek:
    model: "deepseek-chat"
    base_url: "https://api.deepseek.com/v1"
    api_key: "${DEEPSEEK_API_KEY}"
    max_tokens: 8192
    temperature: 0.7

  # Local models via Ollama (commented out by default)
  # ollama:
  #   model: "llama3"
  #   base_url: "http://localhost:11434/v1"
  #   api_key: "ollama"
  #   max_tokens: 4096
  #   temperature: 0.7

# Agent Settings
agents:
  research_team:
    enabled: true
    llm: "llm" # Uses the default LLM configuration
    max_conversation_turns: 5

  robot_brain_team:
    enabled: true
    llm: "llm"
    max_iterations: 3
    design_output_dir: "./design_output"

  embodied_app_team:
    enabled: true
    llm: "llm"
    max_iterations: 3
    design_output_dir: "./design_output"

# Tool Settings
tools:
  embodied:
    enabled: true
    visualize: true
    default_noise_level: 0.05

  web_research:
    enabled: true
    max_results: 5
    search_engine: "google"
    user_agent: "Roboco Research Agent/1.0"

  terminal:
    enabled: true
    allow_destructive_commands: false
    max_execution_time: 30

  arxiv:
    enabled: true
    max_results: 10
    timeout: 30
    rate_limit_delay: 3
    cache_dir: "./cache/arxiv"
    temp_dir: "./tmp/arxiv_papers"

  github:
    enabled: true
    token: "${GITHUB_TOKEN}" # Set in environment or .env file
    max_results: 10
    timeout: 30
    rate_limit_delay: 1
    cache_dir: "./cache/github"

# Server Settings
server:
  host: "127.0.0.1"
  port: 5004
  log_level: "info"
  reload: true

# UI Settings
ui:
  enabled: false
  port: 8000
  host: "127.0.0.1"
  theme: "system"
