name: "WriterReviewerTeam"
description: "A focused team demonstrating orchestration and handoffs between Writer and Reviewer"
output_dir: "workspace"

agents:
  - name: writer
    class: "agentx.core.agents.Agent"
    system_message_file: "config/prompts/writer.md"
    llm_config:
      config_list:
        - model: "deepseek-chat"
          api_key: null

  - name: reviewer
    class: "agentx.core.agents.Agent"
    system_message_file: "config/prompts/reviewer.md"
    llm_config:
      config_list:
        - model: "deepseek-chat"
          api_key: null

# Handoff rules for agent collaboration
handoffs:
  - from: "writer"
    to: "reviewer"
    condition: "draft_complete"
    description: "Writer hands off to reviewer when initial draft is complete"

  - from: "reviewer"
    to: "writer"
    condition: "feedback_provided"
    description: "Reviewer hands back to writer with feedback for revisions"

  - from: "writer"
    to: "reviewer"
    condition: "revision_complete"
    description: "Writer hands off revised content back to reviewer"
