human:
  llm:
    model: gpt-4-turbo-preview
    temperature: 0.7
    timeout: 600
  additional_config:
    human_input_mode: "ALWAYS"

executive_board:
  llm:
    model: gpt-4-turbo-preview
    temperature: 0.7
    timeout: 600
  additional_config:
    human_input_mode: "NEVER"

product_manager:
  llm:
    model: gpt-4-turbo-preview
    temperature: 0.7
    timeout: 600
  additional_config:
    human_input_mode: "NEVER"
