agents: {}
api:
  debug: false
  host: 127.0.0.1
  port: 8000
company:
  contact_email: contact@example.com
  description: ''
  email_signature: ''
  email_templates: {}
  integrations: {}
  logo_path: ''
  name: My Company
  primary_color: '#007BFF'
  secondary_color: '#6C757D'
  support_email: support@example.com
  website: https://example.com
core:
  cache:
    max_size: 1000
    ttl: 3600
    type: memory
  concurrency:
    max_workers: 4
    timeout: 300
  database:
    echo: false
    path: data/roboco.db
    pool_recycle: 3600
    pool_size: 5
    type: sqlite
  features:
    enable_code_execution: true
    enable_file_access: true
    enable_swarm: true
    enable_web_search: true
  security:
    algorithm: HS256
    secret_key: ''
    token_expire_minutes: 1440
  storage:
    max_size_mb: 1024
    root_dir: data/storage
    type: local
extras: {}
llm:
  default_model: gpt_4o
  defaults:
    max_tokens: 4000
    temperature: 0.7
    terminate_msg: TERMINATE
  models: {}
logging:
  file: null
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
projects: {}
teams: {}
tools: {}
workspace_root: /Users/hugh/roboco_workspace
