# VibeX Preset Agent Configurations
# This file defines all preset agents available in the framework

# Default configurations that can be inherited
defaults:
  brain_config:
    provider: "deepseek"
    model: "deepseek/deepseek-chat"
    supports_function_calls: true
    streaming: true
    timeout: 120

  tools:
    - "file_tools"
    - "search"

# Preset agent definitions
# Note: Planning is handled by the orchestrator's Brain, not a separate agent
preset_agents:
  researcher:
    description: "Professional market researcher with industry expertise"
    role: "specialist"
    prompt_file: "agents/researcher.md"
    brain_config:
      provider: "deepseek"
      model: "deepseek/deepseek-chat"
      temperature: 0.2
      max_tokens: 2000
      supports_function_calls: true
      streaming: true
    tools:
      - "research_topic" # Deep adaptive research with crawl4ai 0.7.0
      - "search_web" # Quick web search
      - "extract_urls" # Extract content from specific URLs
      - "read_file"
      - "write_file"
      - "list_files"
      - "list_directory"

  writer:
    description: "Strategic business writer producing executive-quality content"
    role: "specialist"
    prompt_file: "agents/writer.md"
    brain_config:
      provider: "deepseek"
      model: "deepseek/deepseek-chat"
      temperature: 0.3
      max_tokens: 3000
      supports_function_calls: true
      streaming: true
    tools:
      - "read_file"
      - "write_file"
      - "list_files"
      - "list_directory"

  reviewer:
    description: "Quality assurance specialist ensuring executive-level standards"
    role: "specialist"
    prompt_file: "agents/reviewer.md"
    brain_config:
      provider: "deepseek"
      model: "deepseek/deepseek-chat"
      temperature: 0.1
      max_tokens: 2000
      supports_function_calls: true
      streaming: true
    tools:
      - "read_file"
      - "write_file" # Added for saving polished versions
      - "list_files"
      - "list_directory"
      - "polish_document" # New tool using DeepSeek Reasoner

  developer:
    description: "Code implementation specialist for software development"
    role: "specialist"
    prompt_file: "agents/developer.md"
    brain_config:
      provider: "deepseek"
      model: "deepseek/deepseek-coder"
      temperature: 0.2
      max_tokens: 4000
      supports_function_calls: true
      streaming: true
    tools:
      - "read_file"
      - "write_file"
      - "list_files"
      - "list_directory"
      - "delete_file"
      - "create_directory"

  web_designer:
    description: "Professional web designer specializing in modern, responsive HTML websites and interactive experiences"
    role: "specialist"
    prompt_file: "agents/web_designer.md"
    brain_config:
      provider: "deepseek"
      model: "deepseek/deepseek-chat"
      temperature: 0.2
      max_tokens: 4000
      supports_function_calls: true
      streaming: true
    tools:
      - "read_file"
      - "write_file"
      - "list_files"
      - "list_directory"
      - "create_directory"
      - "delete_file"
