# Nixpacks configuration for AgentX Studio
# This file configures the build process for Railway deployment

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "pnpm install --frozen-lockfile"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "pnpm run build"
]

[start]
cmd = "pnpm run start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"