name: "WordX Document Processing Team"
description: "Multi-agent team for professional document review, editing, formatting, and compliance checking"

# Backend configuration
backend:
  type: "memory"
  config:
    provider: "simple"

# Model configuration
models:
  default:
    provider: "deepseek"
    model: "deepseek-chat"
    config:
      temperature: 0.3
      max_tokens: 8000

# Agents configuration
agents:
  - name: "Document Reviewer"
    description: "Analyzes document structure, clarity, and overall quality"
    prompt_file: "prompts/document_reviewer.md"
    tools:
      - "read_file"
      - "write_file"
      - "list_files"

  - name: "Content Editor"
    description: "Improves writing quality, clarity, and engagement"
    prompt_file: "prompts/content_editor.md"
    tools:
      - "read_file"
      - "write_file"
      - "list_files"

  - name: "Formatter"
    description: "Optimizes document layout, styling, and visual presentation"
    prompt_file: "prompts/formatter.md"
    tools:
      - "read_file"
      - "write_file"
      - "list_files"

  - name: "Compliance Auditor"
    description: "Ensures document meets industry standards and compliance requirements"
    prompt_file: "prompts/compliance_auditor.md"
    tools:
      - "read_file"
      - "write_file"
      - "list_files"

# Workflow configuration
workflow:
  orchestrator:
    routing_model: "default"
    max_iterations: 10
    completion_criteria:
      - "All agents have completed their tasks"
      - "Document quality meets professional standards"
      - "User requirements are fully addressed"

  # Agent handoff rules
  handoffs:
    document_reviewer:
      - target: "content_editor"
        condition: "Document structure analysis complete"
        message: "Document analysis complete. Please improve content quality and clarity."

    content_editor:
      - target: "formatter"
        condition: "Content editing complete"
        message: "Content has been improved. Please optimize formatting and presentation."

    formatter:
      - target: "compliance_auditor"
        condition: "Formatting complete"
        message: "Document formatting complete. Please check for compliance issues."

    compliance_auditor:
      - target: "document_reviewer"
        condition: "Compliance issues found"
        message: "Found compliance issues. Please review and address."

# Tool configurations
tools:
  web_search:
    enabled: true
    config:
      max_results: 5
      timeout: 30

  memory:
    enabled: true
    config:
      max_entries: 1000
      retention_days: 30

  file_operations:
    enabled: true
    config:
      allowed_extensions: [".txt", ".md", ".docx", ".pdf"]
      max_file_size: "10MB"

# Processing configuration
processing:
  timeout: 300 # 5 minutes
  max_retries: 3
  parallel_processing: false

  # Quality gates
  quality_gates:
    - name: "Content Quality"
      threshold: 0.8
      agent: "content_editor"

    - name: "Formatting Standards"
      threshold: 0.9
      agent: "formatter"

    - name: "Compliance Check"
      threshold: 0.95
      agent: "compliance_auditor"

# Logging configuration
logging:
  level: "INFO"
  format: "structured"
  capture_agent_thoughts: true
  capture_tool_usage: true
