roles:
  # VersatileTeam roles

  # Researcher
  researcher:
    description: "Researches the problem domain and designs solutions"
    name: Researcher
    type: agent
    llm:
      provider: "anthropic"
      temperature: 0.7
      max_tokens: 4000

  # Creator (Implementation)
  creator:
    description: "Implements solutions based on designs"
    name: Creator
    type: agent
    llm:
      provider: "llm"
      temperature: 0.7
      max_tokens: 4000

  # Evaluator (Testing and Validation)
  evaluator:
    description: "Tests and evaluates implemented solutions"
    name: Evaluator
    type: agent
    llm:
      provider: "llm"
      temperature: 0.5
      max_tokens: 4000

  # Integrator (Integration and Finalization) - formerly Synthesizer
  integrator:
    description: "Integrates and finalizes the complete solution"
    name: Integrator
    type: agent
    llm:
      provider: "llm"
      temperature: 0.6
      max_tokens: 4000
