roles:
  # VersatileTeam roles

  # Researcher
  researcher:
    description: "Researches the problem domain and designs solutions"
    name: Researcher
    type: agent
    llm:
      provider: "deepseek"
      temperature: 0.7
      max_tokens: 4000

  # Developer (Implementation)
  developer:
    description: "Implements solutions based on designs"
    name: Developer
    type: agent
    llm:
      provider: "anthropic"
      temperature: 0.7
      max_tokens: 4000

  # Writer (Content Creation)
  writer:
    description: "Creates written content, reports, and documentation"
    name: Writer
    type: agent
    llm:
      provider: "llm"
      temperature: 0.7
      max_tokens: 4000

  # Evaluator (Testing and Validation)
  evaluator:
    description: "Tests and evaluates implemented solutions"
    name: Evaluator
    type: agent
    llm:
      provider: "llm"
      temperature: 0.5
      max_tokens: 4000

  # Lead (Leadership and Integration) - formerly Integrator
  lead:
    description: "Leads the team and integrates the complete solution"
    name: Lead
    type: agent
    llm:
      provider: "deepseek"
      temperature: 0.6
      max_tokens: 4000
