roles:
  # VersatileTeam roles

  # Researcher
  researcher:
    description: "Researches the problem domain and designs solutions"
    name: Researcher
    llm:
      model: "gpt-4o"
      temperature: 0.7
      max_tokens: 8000

  # Developer (Implementation)
  developer:
    description: "Implements solutions based on designs"
    name: Developer
    llm:
      model: "claude-3-5-sonnet-20241022"
      temperature: 0.3
      max_tokens: 8000

  # Writer (Content Creation)
  writer:
    description: "Creates written content, reports, and documentation"
    name: Writer
    llm:
      model: "gpt-4o"
      temperature: 0.7
      max_tokens: 8192

  # Evaluator (Testing and Validation)
  evaluator:
    description: "Tests and evaluates implemented solutions"
    name: Evaluator
    llm:
      model: "gpt-4o"
      temperature: 0.3
      max_tokens: 8000

  # Lead (Leadership and Integration) - formerly Integrator
  lead:
    description: "Leads the team and integrates the complete solution"
    name: Lead
    llm:
      model: "gpt-4o"
      temperature: 0.4
      max_tokens: 8192

  # Executor
  executor:
    description: "Executes tasks and commands"
    name: Executor
    llm:
      model: "gpt-4o"
      temperature: 0.1
      max_tokens: 8000

  # Planner
  planner:
    description: "Plans and organizes projects"
    name: Planner
    llm:
      model: "gpt-4o"
      temperature: 0.7
      max_tokens: 8000
