roles:
  data_analyst:
    name: Data Analyst
    type: agent
    llm:
      provider: "llm" # Uses default LLM configuration
      temperature: 0.5
      max_tokens: 3000
  executive:
    description: Strategic leadership and final approval of plans
    name: Executive
    type: agent
    llm:
      provider: "llm" # Uses default LLM configuration
      temperature: 0.3 # Lower temperature for more deterministic responses
      max_tokens: 2000
  human_proxy:
    description: Interface between agents and human users
    name: HumanProxy
    type: human_proxy
  product_manager:
    description: Creates and manages product plans and specifications
    name: ProductManager
    type: agent
    llm:
      provider: "openai" # Uses OpenAI configuration
      model: "gpt-4o" # Specifies which model to use
      temperature: 0.7 # Higher temperature for more creative outputs
      max_tokens: 4000
  report_writer:
    description: Documentation and report creation
    name: ReportWriter
    type: agent
    llm:
      provider: "llm" # Uses default LLM configuration
      temperature: 0.6
      max_tokens: 3500
  software_engineer:
    description: Technical implementation and code development
    name: SoftwareEngineer
    type: agent
    llm:
      provider: "deepseek" # Uses DeepSeek configuration for coding tasks
      model: "deepseek-coder"
      temperature: 0.5
      max_tokens: 3000
  robotics_scientist:
    description: Research and development of robotics technology
    name: RoboticsScientist
    type: agent
    llm:
      provider: "openai" # Uses OpenAI for scientific reasoning
      model: "gpt-4o"
      temperature: 0.4 # Balanced temperature for reasoned but flexible thinking
      max_tokens: 4000
