# Roboco Robotics Corporation Organizational Chart
# This file defines the organizational structure and roles within the company

# Organizational Structure
org_structure:
  executive:
    role: "Executive"
    responsibilities:
      - "Strategic decision making"
      - "Company vision and direction"
      - "Resource allocation"
    reports_to: null
    manages:
      - "product_manager"
      - "robotics_scientist"
    tools:
      - "WebSearchTool"
      - "BrowserUseTool"

  product_manager:
    role: "ProductManager"
    responsibilities:
      - "Product strategy"
      - "Feature planning"
      - "Market analysis"
    reports_to: "executive"
    manages:
      - "software_engineer"
    tools:
      - "WebSearchTool"
      - "BrowserUseTool"

  robotics_scientist:
    role: "RoboticsScientist"
    responsibilities:
      - "Research and innovation"
      - "Technical feasibility"
      - "Scientific validation"
    reports_to: "executive"
    collaborates_with:
      - "software_engineer"
    tools:
      - "WebSearchTool"
      - "ArxivTool"
      - "GitHubTool"

  software_engineer:
    role: "SoftwareEngineer"
    responsibilities:
      - "Robot development"
      - "Testing and validation"
      - "Operations and maintenance"
    reports_to: "product_manager"
    collaborates_with:
      - "robotics_scientist"
    tools:
      - "WebSearchTool"
      - "GitHubTool"
      - "BrowserUseTool"

  report_writer:
    role: "ReportWriter"
    responsibilities:
      - "Documentation"
      - "Report generation"
      - "Knowledge management"
    reports_to: "executive"
    collaborates_with:
      - "product_manager"
      - "robotics_scientist"
      - "software_engineer"
    tools:
      - "WebSearchTool"
      - "BrowserUseTool"

  human_proxy:
    role: "HumanProxy"
    responsibilities:
      - "Human interaction"
      - "User feedback"
      - "Stakeholder communication"
    reports_to: "executive"
    collaborates_with: all
    tools:
      - "WebSearchTool"
      - "BrowserUseTool"

# Communication Patterns
communication_patterns:
  swarm:
    enabled: true
    features:
      - "Dynamic task allocation"
      - "Self-organization"
      - "Emergent behavior"
    collaboration_rules:
      - "Agents can communicate with any other agent"
      - "Decisions are made through consensus"
      - "Tasks are distributed based on expertise"
    feedback_loops:
      - "Continuous improvement"
      - "Knowledge sharing"
      - "Performance optimization"

# Team Dynamics
team_dynamics:
  decision_making:
    style: "consensus"
    voting_threshold: 0.75
  conflict_resolution:
    style: "collaborative"
    escalation_path: ["executive"]
  knowledge_sharing:
    style: "open"
    documentation_requirements: "mandatory"
