teams:
  # Planning team configuration
  planning:
    name: "PlanningTeam"
    description: "A team that collaborates to create project planning documents"
    output_dir: "workspace/plan"
    roles:
      - executive
      - product_manager
      - software_engineer
      - report_writer
      - human_proxy
    workflow:
      - from: product_manager
        to: software_engineer
      - from: software_engineer
        to: report_writer
      - from: report_writer
        to: executive
      - from: executive
        to: product_manager
    tools:
      - fs
    tool_executor: human_proxy
