teams:
  # Planning team configuration
  planning:
    name: "PlanningTeam"
    description: "A team that collaborates to create project planning documents"
    output_dir: "workspace/plan"
    roles:
      - executive
      - product_manager
      - software_engineer
      - report_writer
      - human_proxy
    workflow:
      - from: product_manager
        to: software_engineer
      - from: software_engineer
        to: report_writer
      - from: report_writer
        to: executive
      - from: executive
        to: product_manager
    tools:
      - fs
    tool_executor: human_proxy

  # Robotics team configuration
  robotics:
    name: "RoboticsTeam"
    description: "A team that designs, implements and tests robotic systems"
    output_dir: "workspace/robotics"
    roles:
      - executive
      - robotics_scientist
      - software_engineer
      - product_manager
      - human_proxy
    workflow:
      - from: executive
        to: robotics_scientist
      - from: robotics_scientist
        to: software_engineer
      - from: software_engineer
        to: product_manager
      - from: product_manager
        to: executive
    tools:
      - fs
      - browser_use
    tool_executor: human_proxy

  # Development team configuration
  development:
    name: "DevTeam"
    description: "A team focused on software development and implementation"
    output_dir: "workspace/dev"
    roles:
      - software_engineer
      - product_manager
      - report_writer
      - human_proxy
    workflow:
      - from: product_manager
        to: software_engineer
      - from: software_engineer
        to: report_writer
      - from: report_writer
        to: product_manager
    tools:
      - fs
      - browser_use
    tool_executor: human_proxy

  # Research team configuration
  research:
    name: "ResearchTeam"
    description: "A team focused on research and innovation"
    output_dir: "workspace/research"
    roles:
      - executive
      - robotics_scientist
      - software_engineer
      - human_proxy
    workflow:
      - from: executive
        to: robotics_scientist
      - from: robotics_scientist
        to: software_engineer
      - from: software_engineer
        to: executive
    tools:
      - fs
      - browser_use
    tool_executor: human_proxy
