agents:
  - name: planner
    role: "Project planner responsible for creating the initial plan."
    model: "deepseek/deepseek-coder"
    prompt_file: "agents/planner.md"
    tools:
      - write_file

  - name: researcher
    role: "A stateless research specialist that executes a single research task."
    model: "deepseek/deepseek-coder"
    prompt_file: "agents/researcher.md"
    tools:
      - search
      - extract_content_from_url
      - write_file

  - name: writer
    role: "A stateless writing specialist that executes a single writing task."
    model: "deepseek/deepseek-coder"
    prompt_file: "agents/writer.md"
    tools:
      - write_file

  - name: reviewer
    role: "A stateless review specialist that executes a single review task."
    model: "deepseek/deepseek-coder"
    prompt_file: "agents/reviewer.md"
    tools: []
