# AgentX Preset Agent Configurations
# This file defines all preset agents available in the framework

# Default configurations that can be inherited
defaults:
  brain_config:
    provider: "deepseek"
    model: "deepseek/deepseek-chat"
    supports_function_calls: true
    streaming: true
    timeout: 30

  tools:
    - "file_management"
    - "search"

# Preset agent definitions
preset_agents:
  planner:
    description: "Strategic planning and task decomposition specialist"
    role: "specialist"
    prompt_file: "agents/planner.md"
    brain_config:
      provider: "deepseek"
      model: "deepseek/deepseek-chat"
      temperature: 0.1
      max_tokens: 1000
      supports_function_calls: true
      streaming: true
    tools:
      - "file_management"
      - "search"
      - "planning"

  researcher:
    description: "Professional market researcher with industry expertise"
    role: "specialist"
    prompt_file: "agents/researcher.md"
    brain_config:
      provider: "deepseek"
      model: "deepseek/deepseek-chat"
      temperature: 0.2
      max_tokens: 2000
      supports_function_calls: true
      streaming: true
    tools:
      - "web_search"
      - "file_management"
      - "search"
      - "context_tools"

  writer:
    description: "Strategic business writer producing executive-quality content"
    role: "specialist"
    prompt_file: "agents/writer.md"
    brain_config:
      provider: "deepseek"
      model: "deepseek/deepseek-chat"
      temperature: 0.3
      max_tokens: 3000
      supports_function_calls: true
      streaming: true
    tools:
      - "file_management"
      - "search"
      - "storage_tools"

  reviewer:
    description: "Quality assurance specialist ensuring executive-level standards"
    role: "specialist"
    prompt_file: "agents/reviewer.md"
    brain_config:
      provider: "deepseek"
      model: "deepseek/deepseek-chat"
      temperature: 0.1
      max_tokens: 2000
      supports_function_calls: true
      streaming: true
    tools:
      - "file_management"
      - "search"

  developer:
    description: "Code implementation specialist for software development"
    role: "specialist"
    prompt_file: "agents/developer.md"
    brain_config:
      provider: "deepseek"
      model: "deepseek/deepseek-coder"
      temperature: 0.2
      max_tokens: 4000
      supports_function_calls: true
      streaming: true
    tools:
      - "file_management"
      - "search"
      - "storage_tools"

  document_formatter:
    description: "Universal document formatter supporting HTML, PDF, Word, and other professional formats"
    role: "specialist"
    prompt_file: "agents/document_formatter.md"
    brain_config:
      provider: "deepseek"
      model: "deepseek/deepseek-chat"
      temperature: 0.1
      max_tokens: 4000
      supports_function_calls: true
      streaming: true
    tools:
      - "file_management"
      - "search"
      - "storage_tools"
