agents:
  - name: planner
    class: agentx.core.agents.Agent
    prompt_file: planner.md
    tools: []
    llm_config:
      config_list:
        - model: gpt-4o-mini
          api_key: null
  - name: researcher
    class: agentx.core.agents.Agent
    prompt_file: researcher.md
    tools:
      - search_tools
    llm_config:
      config_list:
        - model: gpt-4o-mini
          api_key: null
  - name: writer
    class: agentx.core.agents.Agent
    prompt_file: writer.md
    tools: []
    llm_config:
      config_list:
        - model: gpt-4o-mini
          api_key: null
  - name: reviewer
    class: agentx.core.agents.Agent
    prompt_file: reviewer.md
    tools: []
    llm_config:
      config_list:
        - model: gpt-4o-mini
          api_key: null
memory:
  vector_store:
    provider: chroma
    config:
      collection_name: superwriter_research
      path: ./workspace/memory_db
  llm:
    provider: openai
    config:
      model: gpt-4o-mini
      temperature: 0.1
      max_tokens: 2048
  embedder:
    provider: openai
    config:
      model: text-embedding-3-small
  version: v1.1
team:
  max_rounds: 50
  speaker_selection_method: round_robin
  allow_repeat_speaker: true
  enable_function_calls: true
  human_input_mode: NEVER
events:
  bus_type: memory
  persistence: true
  auto_emit_patterns:
    - metadata_filter:
        artifact_type: document
        status: final
      event_name: document_created
    - metadata_filter:
        artifact_type: plan
        status: approved
      event_name: plan_created
    - metadata_filter:
        artifact_type: research
        status: complete
      event_name: research_completed
    - metadata_filter:
        artifact_type: section
        status: approved
      event_name: section_completed
workflow:
  phases:
    - name: requirements_gathering
      agents:
        - planner
      completion_criteria: requirements_finalized
    - name: execution_planning
      agents:
        - planner
      completion_criteria: execution_plan_created
    - name: research
      agents:
        - researcher
        - reviewer
      completion_criteria: sources_sufficient
    - name: writing
      agents:
        - writer
        - reviewer
      completion_criteria: sections_approved
    - name: compilation
      agents:
        - writer
        - reviewer
      completion_criteria: document_approved
  handoff_patterns:
    - from: user
      to: planner
      trigger: raw_request
    - from: planner
      to: planner
      trigger: survey_completed
    - from: planner
      to: researcher
      trigger: execution_plan_ready
    - from: researcher
      to: reviewer
      trigger: sources_gathered
    - from: reviewer
      to: researcher
      trigger: sources_insufficient
    - from: reviewer
      to: writer
      trigger: sources_sufficient
    - from: writer
      to: reviewer
      trigger: section_drafted
    - from: reviewer
      to: writer
      trigger: section_needs_revision
    - from: reviewer
      to: researcher
      trigger: more_sources_needed
    - from: writer
      to: reviewer
      trigger: document_compiled
    - from: reviewer
      to: writer
      trigger: document_needs_revision
    - from: reviewer
      to: user
      trigger: document_approved
