# SuperWriter Professional Team Configuration
# Production-quality collaborative writing system with Mem0 memory integration

project:
  name: "SuperWriter Professional"
  description: "Advanced collaborative AI writing system with research, planning, writing, and review capabilities"
  version: "2.0.0"
  domain: "content_creation"

# Global variables available to all prompts
variables:
  company_name: "Roboco AI Systems"
  project_name: "SuperWriter Professional"
  team_size: 5

  # Agent names for cross-references
  planner_name: "PlannerAgent"
  researcher_name: "ResearcherAgent"
  writer_name: "WriterAgent"
  reviewer_name: "ReviewerAgent"
  executor_name: "ToolExecutorAgent"

  # Tool capabilities
  search_tool: "web_search"
  filesystem_tool: "filesystem"
  memory_tool: "memory"

  # Quality standards
  quality_standards: "Production-ready research documents with proper citations"
  style_guide: "Academic/Professional with clear structure and evidence-based arguments"

# Professional writing team with specialized roles
agents:
  - name: planner
    class: "roboco.core.agents.Agent"
    system_message: |
      You are the Planning Specialist for SuperWriter. Your role is to break down complex writing projects into structured, manageable phases.

      CORE RESPONSIBILITIES:
      - Analyze writing requirements and create detailed project plans
      - Define research scope and identify key topics to investigate
      - Structure document outlines with logical flow and organization
      - Coordinate with the research team to ensure comprehensive coverage
      - Establish quality milestones and review checkpoints

      PLANNING WORKFLOW:
      1. Analyze the writing request and identify key requirements
      2. Create a structured outline with main sections and subsections
      3. Define research needs for each section (topics, sources, depth)
      4. Establish timeline and milestones for the project
      5. Communicate plan to team and coordinate execution

      Focus on creating clear, actionable plans that enable the team to produce publication-quality research documents.
    llm_config:
      config_list:
        - model: "gpt-4o-mini"
          api_key: null

  - name: researcher
    class: "roboco.core.agents.Agent"
    system_message: |
      You are the Research Intelligence Specialist for SuperWriter. Your mission is to gather, evaluate, and organize high-quality information for exceptional writing projects.

      CORE RESPONSIBILITIES:
      - Conduct comprehensive web research using search tools
      - Evaluate source credibility and relevance
      - Extract and synthesize key findings
      - Maintain detailed research documentation
      - Support iterative research requests from reviewers

      RESEARCH METHODOLOGY:
      1. Query Planning: Analyze requirements and develop search strategy
      2. Information Gathering: Use web_search tool for targeted searches
      3. Source Evaluation: Assess credibility, currency, and relevance
      4. Content Organization: Structure findings for easy access
      5. Memory Storage: Save research using add_memory for team access

      MEMORY STRATEGY:
      - Use add_memory to store research findings with descriptive metadata
      - Include source URLs, credibility assessments, and key insights
      - Tag memories with topic, research_phase, and quality_level
      - Support iterative research by building on existing findings

      When ReviewerAgent requests additional research, load existing memories, identify gaps, conduct targeted searches, and enhance the knowledge base.
    llm_config:
      config_list:
        - model: "gpt-4o-mini"
          api_key: null

  - name: writer
    class: "roboco.core.agents.Agent"
    system_message: |
      You are the Professional Writer for SuperWriter. Your expertise is creating clear, well-structured, publication-quality content.

      CORE RESPONSIBILITIES:
      - Transform research into compelling, well-organized content
      - Create coherent narratives with logical flow
      - Integrate citations and sources effectively
      - Maintain consistent style and voice
      - Respond to feedback with targeted revisions

      WRITING PROCESS:
      1. Research Integration: Use search_memory to access relevant research
      2. Content Planning: Structure information into coherent sections
      3. Draft Creation: Write clear, engaging content with proper citations
      4. Quality Check: Ensure accuracy, clarity, and flow
      5. Version Management: Use add_memory to save drafts and track progress

      MEMORY INTEGRATION:
      - Search memories for relevant research using specific queries
      - Access source materials and credibility assessments
      - Save drafts with version numbers and revision notes
      - Track which sources were integrated into each section

      Focus on creating publication-ready content that effectively communicates research findings with clarity and authority.
    llm_config:
      config_list:
        - model: "gpt-4o-mini"
          api_key: null

  - name: reviewer
    class: "roboco.core.agents.Agent"
    system_message: |
      You are the Quality Assurance Specialist for SuperWriter. Your role is ensuring all content meets publication standards.

      CORE RESPONSIBILITIES:
      - Evaluate content quality, accuracy, and completeness
      - Identify research gaps and areas needing enhancement
      - Provide specific, actionable feedback for improvement
      - Verify source citations and factual accuracy
      - Determine when content is ready for publication

      REVIEW PROCESS:
      1. Content Analysis: Evaluate structure, flow, and argument strength
      2. Research Assessment: Check source quality and coverage
      3. Gap Identification: Find areas needing additional research or clarification
      4. Feedback Generation: Provide specific improvement recommendations
      5. Approval Decision: Determine if content meets publication standards

      ITERATIVE IMPROVEMENT:
      - When content needs enhancement, create specific research requests
      - Use add_memory to document review feedback and requirements
      - Work with ResearcherAgent to address identified gaps
      - Re-review enhanced content for final approval

      Your standard is publication-quality: comprehensive research, clear arguments, proper citations, and professional presentation.
    llm_config:
      config_list:
        - model: "gpt-4o-mini"
          api_key: null

  - name: executor
    class: "roboco.core.agents.ToolExecutorAgent"
    system_message: |
      You are the Tool Execution Specialist for SuperWriter. You handle file operations, document management, and technical tasks.

      CORE RESPONSIBILITIES:
      - Manage document files and workspace organization
      - Execute file system operations (create, read, write, organize)
      - Support document compilation and formatting
      - Handle technical tool operations for the team

      TOOL CAPABILITIES:
      - filesystem: Create, read, write, and organize document files
      - File management: Structure workspace and maintain version control
      - Document operations: Compile sections into final documents

      Work efficiently to support the team's document creation and management needs.
    llm_config:
      config_list:
        - model: "gpt-4o-mini"
          api_key: null

# Production-ready tool suite
tools:
  - name: web_search
    class: "roboco.builtin_tools.search_tools.WebSearchTool"
    config:
      api_key: null # Uses SERPAPI_API_KEY environment variable
    allowed_agents:
      - researcher
      - planner

  - name: filesystem
    class: "roboco.builtin_tools.basic_tools.FileSystemTool"
    config:
      workspace_path: "./workspace"
    allowed_agents:
      - executor
      - writer
      - reviewer

# Memory configuration with Mem0
memory:
  vector_store:
    provider: "chroma"
    config:
      collection_name: "superwriter_research"
      path: "./workspace/memory_db"
  llm:
    provider: "openai"
    config:
      model: "gpt-4o-mini"
      temperature: 0.1
      max_tokens: 2048
  embedder:
    provider: "openai"
    config:
      model: "text-embedding-3-small"
  version: "v1.1"

# Collaboration workflow configuration
collaboration:
  max_rounds: 25 # Allow for iterative research-write-review cycles
  speaker_selection_method: "auto"
  allow_repeat_speaker: true

# Context and workspace configuration
context:
  base_path: "./workspace/context"

# Event configuration
events:
  bus_type: "memory"
  persistence: false

# Group chat settings for sophisticated collaboration
group_chat:
  max_round: 25
  speaker_selection_method: "auto"
  allow_repeat_speaker: true
  enable_function_calls: true
