# Nixpacks configuration for VibeX Web Interface
# This is for deploying the web interface separately from the API

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"